// Dev-time tool, NOT used by the workflow. Regenerates scripts/glyphs.py:
// Space Grotesk outlines (as SVG path data) for printable ASCII plus a few
// symbols, so the SVG needs no web font (GitHub serves SVGs in a sandbox that
// blocks them). Run only if you change the glyph set or weights:
//   npm i opentype.js @fontsource/space-grotesk
//   node scripts/dev/make_glyphs.js > scripts/glyphs.py
const opentype = require('opentype.js');
const path = require('path');
const fs = require('fs');
const dir = path.dirname(require.resolve('@fontsource/space-grotesk/package.json')) + '/files/';
const chars = [];
for (let c = 32; c <= 126; c++) chars.push(String.fromCharCode(c));
chars.push('·');
const out = ['# Generated by scripts/dev/make_glyphs.js. Do not edit.',
  '# Space Grotesk (SIL OFL 1.1) outlines. Paths are in font units, y-down, baseline at y=0.',
  'GLYPHS = {'];
for (const w of ['500', '700']) {
  const buf = fs.readFileSync(dir + `space-grotesk-latin-${w}-normal.woff`);
  const font = opentype.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength));
  const upem = font.unitsPerEm;
  out.push(`    "${w}": {"upem": ${upem}, "glyphs": {`);
  for (const ch of chars) {
    const g = font.charToGlyph(ch);
    const d = g.getPath(0, 0, upem).toPathData(1);
    out.push(`        ${JSON.stringify(ch)}: (${g.advanceWidth}, ${JSON.stringify(d)}),`);
  }
  out.push('    }},');
}
out.push('}');
console.log(out.join('\n'));
